name: Angular deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
jobs:
  build:
    # using Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BotSoundboardFront/BotSoundboardFront
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: "Push to server"
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password : ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "/home/runner/work/bot-soundboard-front/bot-soundboard-front/BotSoundboardFront/BotSoundboardFront"
        strip_components: 4
        target: "/var/www/bot-soundboard-front/"
      
    - name: Restarting nginx
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: npm install;ng build --configuration=production;sudo /etc/init.d/nginx restart;cd /var/www/bot-soundboard-back/;pm2 start bot-soundboard-pm2.json;pm2 restart bot-soundboard-back
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
